# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='logo_clientes',
            field=models.ImageField(upload_to='static/img', verbose_name='Logo do Cliente'),
        ),
    ]
