# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190511_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='titulo_clientes',
            field=models.SlugField(default=datetime.datetime(2019, 5, 11, 22, 4, 45, 731988, tzinfo=utc), verbose_name='Titulo do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inicio',
            name='titulo_inicio',
            field=models.SlugField(default=datetime.datetime(2019, 5, 11, 22, 4, 55, 372258, tzinfo=utc), verbose_name='Titulo do Inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quem_somos',
            name='titulo_quem_somos',
            field=models.SlugField(default=datetime.datetime(2019, 5, 11, 22, 5, 2, 163852, tzinfo=utc), verbose_name='Titulo de Quem Somos'),
            preserve_default=False,
        ),
    ]
