# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 22:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='abc',
            field=models.TextField(default=datetime.datetime(2019, 5, 11, 22, 12, 21, 536572, tzinfo=utc), verbose_name='abc'),
            preserve_default=False,
        ),
    ]
