# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientes_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='abc',
        ),
    ]
