# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_clientes_abc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='titulo_clientes',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='inicio',
            old_name='titulo_inicio',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='quem_somos',
            old_name='titulo_quem_somos',
            new_name='titulo',
        ),
    ]
