# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190511_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.SlugField(default='titulo', verbose_name='Titulo do Portifolio')),
                ('img_portfolio', models.ImageField(upload_to='media/img/img_portfolio', verbose_name='Imagem do Portifolio')),
                ('desc_portfolio', models.TextField(verbose_name='Quem Somos')),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='logo_clientes',
            field=models.ImageField(upload_to='media/img/img_clientes', verbose_name='Logo do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='titulo',
            field=models.SlugField(default='titulo', verbose_name='Titulo do Cliente'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='img_inico',
            field=models.ImageField(upload_to='media/img/img_inicio', verbose_name='Imagem do Inicio'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.SlugField(default='titulo', verbose_name='Titulo do Inicio'),
        ),
        migrations.AlterField(
            model_name='quem_somos',
            name='img_quem_somos',
            field=models.ImageField(upload_to='media/img/img_quem_somos', verbose_name='Imagem de Quem Somos'),
        ),
        migrations.AlterField(
            model_name='quem_somos',
            name='titulo',
            field=models.SlugField(default='titulo', verbose_name='Titulo de Quem Somos'),
        ),
    ]
