# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190511_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Inicio', 'verbose_name_plural': 'Inicio'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portifólio', 'verbose_name_plural': 'Portifólios'},
        ),
        migrations.AlterModelOptions(
            name='quem_somos',
            options={'verbose_name': 'Quem Somos', 'verbose_name_plural': 'Quem somos'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100, verbose_name='Titulo do Cliente'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100, verbose_name='Titulo do Inicio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100, verbose_name='Titulo do Portifolio'),
        ),
        migrations.AlterField(
            model_name='quem_somos',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100, verbose_name='Titulo de Quem Somos'),
        ),
    ]
