# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190515_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='logo_clientes',
            field=models.ImageField(upload_to='img/img_clientes', verbose_name='Logo do Cliente'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='img_inico',
            field=models.ImageField(upload_to='img/img_inicio', verbose_name='Imagem do Inicio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img_portfolio',
            field=models.ImageField(upload_to='img/img_portfolio', verbose_name='Imagem do Portifólio'),
        ),
        migrations.AlterField(
            model_name='quem_somos',
            name='img_quem_somos',
            field=models.ImageField(upload_to='img/img_quem_somos', verbose_name='Imagem de Quem Somos'),
        ),
        migrations.AlterField(
            model_name='serviços',
            name='img_serviço',
            field=models.ImageField(upload_to='img/img_serviço', verbose_name='Imagem do Serviço'),
        ),
    ]
