# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190515_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Início', 'verbose_name_plural': 'Início'},
        ),
        migrations.AddField(
            model_name='inicio',
            name='subtitulo',
            field=models.TextField(default='subtitulo', verbose_name='Subtitulo do Inicio'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='txt_butão',
            field=models.TextField(default='texto do botao', verbose_name='Texto do botão'),
        ),
    ]
