# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190516_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='img_inico',
            new_name='img_inic',
        ),
        migrations.RenameField(
            model_name='inicio',
            old_name='subtitulo',
            new_name='subtit_inic',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='txt_butão',
        ),
        migrations.AddField(
            model_name='inicio',
            name='tit_inic',
            field=models.TextField(default='Titulo do Inicio', verbose_name='Titulo do Inicio'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='txt_bt_inic',
            field=models.CharField(default='texto do botao', max_length=100, verbose_name='Texto do botão'),
        ),
        migrations.AddField(
            model_name='quem_somos',
            name='tit_quem_somos',
            field=models.TextField(default='Descrição do projeto', verbose_name='Titulo da descrição do projeto'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='titulo',
            field=models.CharField(default='Cliente', max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(default='Inicio', max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='quem_somos',
            name='titulo',
            field=models.CharField(default='Quem Somos', max_length=100, verbose_name='Titulo'),
        ),
    ]
