# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-18 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190516_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='txt_bt_inic',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='desc_portfolio',
            field=models.TextField(verbose_name='Descrição do projeto'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100, verbose_name='Titulo do Projeto'),
        ),
        migrations.AlterField(
            model_name='serviços',
            name='desc_serviço',
            field=models.TextField(verbose_name='Descrição do Serviço'),
        ),
    ]
